---

version: '3'

services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: "php-directory"
    volumes:
      - ./app:/var/www/html
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    restart: "unless-stopped"
    depends_on:
      - postgres
    networks:
      - directory-network

  nginx:
    image: nginx:1.20
    container_name: "nginx-directory"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - directory-network

  postgres:
    image: postgres:13
    container_name: "postgres-directory"
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./app/.env
    volumes:
      - dbdata-directory:/var/lib/postgresql/data
    networks:
      - directory-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-directory"
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - directory-network

networks:
  directory-network:
    driver: bridge

volumes:
  dbdata-directory:
    driver: local