#index:
#    path: /
#    controller: App\Controller\DefaultController::index
upload:
    path: /upload
    controller: App\Controller\HandbookController::index

upload-new:
    path: /upload-new
    controller: App\Controller\HandbookController::new